### ISSUE TITLE
Clarify that "Mount MinIO storage into the minio/ folder" is for notebook servers only

### ISSUE THREAD

**Issue by ToucheSir** [StatCan/kubeflow-controller#29]
This is mentioned in https://statcan.github.io/daaas/en/5-Storage/MinIO/#minio-mounted-folders-on-a-notebook-server, but Kubeflow still permits the option to be selected when using the `remote-desktop` image. I've no clue if it's possible to include conditional logic for removing options or displaying warning messages in the new server form, but if so it would be nice to have 🙂

**Comment by chuckbelisle** [comment]
Hi @ToucheSir the MinIO documentation was recently removed as we are transitioning our Storage control layer to a new tech stack called Blob-CSI. 

Note that MinIO is still currently live in AAW, but so is the new Blob-CSI feature https://statcan.github.io/aaw/en/5-Storage/AzureBlobStorage/#blob-container-mounted-on-a-notebook-server.
For the time being I will be closing this issue and you are more than welcome to create another one if this is still present.

Second note, we are in the middle of upgrading Kubeflow to the latest version, v1.7. I welcome you to communicate with us through our Slack support channel https://stacan-aaw.slack.com if the UI is still allowing you to do so when the new version goes live.
